[project]
name = "rembg-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.2.0",
    "rembg[cpu]>=2.0.75",
    "rich>=15.0.0",
    "typer>=0.27.2",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]

[tool.ruff.lint]
select = [
    "E4",  # import related pycodestyle
    "E7",  # suspicious syntax
    "E9",  # SyntaxError etc.
    "F",   # Pyflakes
    "I",   # import organization
    "UP",  # update old Python code to new style
    "B",   # common bugs and dangerous code
    "SIM", # simplify unnecessarily complex code
    "C4",  # improve list/dict/set comprehension
    "RUF", # useful checks specific to Ruff
]
ignore = [
    "E501",   # line length is left to the formatter
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
